#!/usr/bin/env python3
import unittest
'''
import os
import sys

file_path = os.path.dirname(os.path.abspath(__file__))
root_path = file_path.replace('/mechanisms/tests', '')

sys.path.append(root_path) if root_path not in sys.path else None
'''
from mechanisms.core.pokemon import Pokemon, Trainer
from mechanisms.data import tables as tb

class TestPokemon(unittest.TestCase):

    def setUp(self):
        pass
